// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/pkg/agent/controller/l7networkpolicy/suricata (interfaces: EnforcerOperations)

// Package testing is a generated GoMock package.
package testing

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockEnforcerOperations is a mock of EnforcerOperations interface
type MockEnforcerOperations struct {
	ctrl     *gomock.Controller
	recorder *MockEnforcerOperationsMockRecorder
}

// MockEnforcerOperationsMockRecorder is the mock recorder for MockEnforcerOperations
type MockEnforcerOperationsMockRecorder struct {
	mock *MockEnforcerOperations
}

// NewMockEnforcerOperations creates a new mock instance
func NewMockEnforcerOperations(ctrl *gomock.Controller) *MockEnforcerOperations {
	mock := &MockEnforcerOperations{ctrl: ctrl}
	mock.recorder = &MockEnforcerOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEnforcerOperations) EXPECT() *MockEnforcerOperationsMockRecorder {
	return m.recorder
}

// ReloadSignatures mocks base method
func (m *MockEnforcerOperations) ReloadSignatures() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReloadSignatures")
}

// ReloadSignatures indicates an expected call of ReloadSignatures
func (mr *MockEnforcerOperationsMockRecorder) ReloadSignatures() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadSignatures", reflect.TypeOf((*MockEnforcerOperations)(nil).ReloadSignatures))
}

// SyncAddressGroups mocks base method
func (m *MockEnforcerOperations) SyncAddressGroups() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAddressGroups")
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncAddressGroups indicates an expected call of SyncAddressGroups
func (mr *MockEnforcerOperationsMockRecorder) SyncAddressGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAddressGroups", reflect.TypeOf((*MockEnforcerOperations)(nil).SyncAddressGroups))
}

// SyncPortGroups mocks base method
func (m *MockEnforcerOperations) SyncPortGroups() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncPortGroups")
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncPortGroups indicates an expected call of SyncPortGroups
func (mr *MockEnforcerOperationsMockRecorder) SyncPortGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPortGroups", reflect.TypeOf((*MockEnforcerOperations)(nil).SyncPortGroups))
}

// SyncSignatures mocks base method
func (m *MockEnforcerOperations) SyncSignatures() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncSignatures")
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncSignatures indicates an expected call of SyncSignatures
func (mr *MockEnforcerOperationsMockRecorder) SyncSignatures() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncSignatures", reflect.TypeOf((*MockEnforcerOperations)(nil).SyncSignatures))
}
