name: Go
on:
  pull_request:
    branches:
    - main
    - release-*
    - feature/*
  push:
    branches:
    - main
    - release-*
    - feature/*

env:
  go-cache-name: go

jobs:
  tidy-codegen-manifest:
    name: Check tidy, code generation and manifest
    runs-on: [ubuntu-latest]
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    # tidy check need to be run before code generation which will regenerate codes.
    - name: Check tidy
      run: make test-tidy
    - name: Check code generation
      run: ./ci/check-codegen.sh
    - name: Check manifest
      run: ./ci/check-manifest.sh
    - name: Check copyright
      run: ./ci/check-copyright.sh