name: Kind
on:
  pull_request:
    branches:
    - main
    - release-*
  push:
    branches:
    - main
    - release-*

env:
  KIND_VERSION: v0.11.1

jobs:
  build-antrea-coverage-image:
    name: Build Antrea image to be used for Kind e2e tests
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build Antrea Docker image with code coverage support
      run: |
        ./hack/build-antrea-ubuntu-all.sh --pull --coverage
    - name: Save Antrea image to tarball
      run:  docker save -o antrea-ubuntu.tar antrea/antrea-ubuntu-coverage:latest
    - name: Upload Antrea image for subsequent jobs
      uses: actions/upload-artifact@v2
      with:
        name: antrea-ubuntu-cov
        path: antrea-ubuntu.tar
        retention-days: 1 # minimum value, in case artifact deletion by 'artifact-cleanup' job fails

  test-e2e-noencap:
    name: E2e tests on a Kind cluster on Linux (noEncap)
    needs: [build-antrea-coverage-image]
    runs-on: [ubuntu-latest]
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        sudo apt-get clean
        df -h
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Download Antrea images from previous jobs
      uses: actions/download-artifact@v2
    - name: Load Antrea image
      run: |
        docker load -i antrea-ubuntu-cov/antrea-ubuntu.tar
    - name: Install Kind
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin
    - name: Run e2e tests
      run: |
        mkdir log
        mkdir test-e2e-noencap-coverage
        ANTREA_LOG_DIR=$PWD/log ANTREA_COV_DIR=$PWD/test-e2e-noencap-coverage ./ci/kind/test-e2e-kind.sh --encap-mode noEncap --coverage --skip mode-irrelevant
    - name: Tar coverage files
      run: tar -czf test-e2e-noencap-coverage.tar.gz test-e2e-noencap-coverage
    - name: Upload coverage for test-e2e-noencap-coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-e2e-noencap-coverage
        path: test-e2e-noencap-coverage.tar.gz
        retention-days: 30
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: '*.cov.out*'
        flags: kind-e2e-tests
        name: codecov-test-e2e-noencap
        directory: test-e2e-noencap-coverage
    - name: Tar log files
      if: ${{ failure() }}
      run: tar -czf log.tar.gz log
    - name: Upload test log
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: e2e-kind-noencap.tar.gz
        path: log.tar.gz
        retention-days: 30
